helm-extra-args: --timeout 300s
check-version-increment: false
debug: true
target-branch: main
chart-dirs:
  - Charts
chart-repos:
  - reloader=https://stakater.github.io/stakater-charts
  - qtest=https://tricentis.github.io/qTest.Charts
remote: origin
validate-maintainers: false
