# Default values for qtest-i-etl-chart
namespace:
  name: qtest

secrets:
  enabled: false
  name: qtest-i-etl-secret

image:
  repository: qasymphony/i-etl
  pullPolicy: IfNotPresent
  tag: "2025.2.0"

liquibase:
  enabled: true
  securityContext: {}
  annotations:
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
  dependencyAnnotations:
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation

imageCredentials:
  enabled: false
  # name: ""
  # registry: ""
  # username: ""
  # password: ""
  # email: ""
  # existingImageCredentials: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # A service account will be created for you if set to true. Set to false if you want to use your own.
  name: "qtest-insights-i-etl-sa"

deployment:
  annotations: {}
  singlePodPerNode: false
  strategy:
    type: Recreate

podAnnotations: {}

rollouts:
  enabled: false
  ingressClassName: alb
  strategy:
    canary:
      maxSurge: "25%"
      maxUnavailable: 0
  steps:
    # if prometheus metrics are enabled
    # - analysis:
    #     templates:
    #     - templateName: success-rates
    #       clusterScope: true
    #     args:
    #     - name: service-name
    - setWeight: 50

extraInitContainers: []

extraContainers: []

extraEnv: []

extraVolumeMounts: []

extraVolumes: []

service:
  type: ClusterIP
  annotations: {}
  port: 8080
  targetPort: 8080
  serviceName: insights-i-etl
securityContext:
  runAsUser: 8877
  runAsNonRoot: true
  fsGroup: 8877

qTestInsightsIEtl:
  readQTestDBHost: postgres.local
  readQTestDBPort: 5432
  readQTestDBName: qtest
  readQTestDBUser: postgres
  writeQTestDBHost: postgres.local
  writeQTestDBPort: 5432
  writeQTestDBName: qtest
  writeQTestDBUser: postgres
  qTestDBSchema: public
  insightsDBSchema: insights
  insightsDBUser: postgres
  insightEtlDBSchema: insights_etl
  iEtlQuartzThreadCount: 10
  iEtlBatchInitialSize: 10000
  iEtlBatchMinSize: 1000
  iEtlBatchMaxSize: "1000000"
  iEtlBatchSleepPercentage: 50
  iEtlBatchOptimalDurationSeconds: 60
  iEtlAggregationInterval: 600
  iEtlMaterializedViewInterval: 600
  iEtlBetaJobsDisabled: false
  logEnvironment: opk8s
  qTestDBPassword: ""
  insightsDBPassword: ""

#### Ingress/IngressClass
ingressClass:
  enabled: false
  labels: {}
  controller: ingress.k8s.aws/alb
  isDefaultClass: true
  # Use to force a networking.k8s.io API Version for certain CI/CD applications. Ex. "v1"
  fallbackApiVersion: ""

ingress:
  enabled: false
  name: qtest-insights-i-etl-ingress
  labels: {}
  annotations: {}
  canary:
    annotationPrefix: ""
    annotations:
      {}
  hosts:
    - host: insights-i-etl.qtest.local

  paths: []

  extraPaths:
    - path: /*
      backendServiceName: insights-i-etl
      pathType: ImplementationSpecific
      backendPort: 8080

  tls:
    []
    # - secretName: qtest-svc-tls
    #   hosts:
    #     - svc.qtest.com
  https: false

# HPA values
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1

  livenessProbe:
    httpGet:
      path: /healthz
      scheme: HTTP
      port: 8080
    initialDelaySeconds: 15
    periodSeconds: 15
    failureThreshold: 3

  readinessProbe:
    httpGet:
      path: /healthz
      scheme: HTTP
      port: 8080
    initialDelaySeconds: 15
    periodSeconds: 15
    failureThreshold: 3

  startupProbe:
    httpGet:
      path: /healthz
      scheme: HTTP
      port: 8080
    initialDelaySeconds: 10
    periodSeconds: 5
    failureThreshold: 20

  targetCPUUtilizationPercentage: 85
  targetMemoryUtilizationPercentage: 85

resources:
  requests:
    cpu: 1
    memory: 2Gi
  limits:
    cpu: 1
    memory: 2Gi

nodeSelector: {}

tolerations: []

affinity: {}

topologySpreadConstraints: {}
