apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.serviceName }}
  namespace: {{ .Values.namespace.name }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: {{ include "qtest-pulse.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
    {{- if .Values.qTestPulse.qTestPulseSSLRequired }}
    - name: https
      protocol: TCP
      port: {{ .Values.service.targetHttpsPort }}
      targetPort: {{ .Values.service.targetHttpsPort }}
    {{- else }}
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
    {{- end }}
    - name: websocket
      protocol: TCP
      port: {{ .Values.service.websocketPort }}
      targetPort: {{ .Values.service.targetWebsocketPort }}
  selector:
    app: {{ include "qtest-pulse.name" . }}
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
---
{{- if .Values.rollouts.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.serviceName }}-canary
  namespace: {{ .Values.namespace.name }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: {{ include "qtest-pulse.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
    {{- if .Values.qTestPulse.qTestPulseSSLRequired }}
    - name: https
      protocol: TCP
      port: {{ .Values.service.targetHttpsPort }}
      targetPort: {{ .Values.service.targetHttpsPort }}
    {{- else }}
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
    {{- end }}
    - name: websocket
      protocol: TCP
      port: {{ .Values.service.websocketPort }}
      targetPort: {{ .Values.service.targetWebsocketPort }}
  selector:
    app: {{ include "qtest-pulse.name" . }}
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
{{- end }}