# Default values for qtest-pulse-chart.
namespace:
  name: qtest
reloader:
  enabled: false
secrets:
  name: qtest-manager-secret
image:
  repository: qasymphony/pulse
  pullPolicy: IfNotPresent
  tag: "2025.2.0"
imageCredentials:
  enabled: false
  # name: ""
  # registry: ""
  # username: ""
  # password: ""
  # email: ""
  # existingImageCredentials: ""
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # A service account will be created for you if set to true. Set to false if you want to use your own.
  name: "qtest-pulse-sa"
deployment:
  annotations: {}
  singlePodPerNode: false
podAnnotations: {}
rollouts:
  enabled: false
  ingressClassName: alb
  strategy:
    canary:
      maxSurge: "25%"
      maxUnavailable: 0
  steps:
    - setWeight: 20
    # if prometheus metrics are enabled
    # - analysis:
    #     templates:
    #     - templateName: success-rates
    #       clusterScope: true
    #     args:
    #     - name: service-name
    - setWeight: 50
    - pause: {duration: 10s}
service:
  type: LoadBalancer
  annotations: {}
  port: 4080
  targetPort: 4080
  targetHttpsPort: 4443
  websocketPort: 6001
  targetWebsocketPort: 6001
  serviceName: qtest-pulse-service
extraInitContainers: []
extraContainers: []
extraArgs: []
extraEnv: []
extraVolumeMounts: []
extraVolumes: []
qTestPulse:
  qTestPulseDBName: pulse
  qTestPulseDBUserName: postgres
  qTestPulseDBHostName: host.docker.internal
  qTestPulseDBPort: "5432"
  qTestPulseNodeEnv: production
  qTestPulseRootURL: https://pulse.qtest.local
  qTestPulseQTestURL: https://nephele.qtest.local
  qTestPulseScenarioURL: https://scenario.local
  qTestPulseNodeTLSRejectUnAuthorized: "0"
  qTestPulseDBSSLEnable: false
  qTestPulseSSLRequired: false
  qTestPulseSSLMountPath: "/mnt/secrets/tls"
  qTestPulseDBSSLMountPath: "/etc/ssl"
  qTestPulseDBSSL: ""
  qTestPulseDBCRT: ""
  # Array of cipher suites for SSL/TLS connection in OpenSSL format (e.g. ["TLS_AES_256_GCM_SHA384", "TLS_CHACHA20_POLY1305_SHA256"])
  qTestPulseSSLCipherSuites: []
  qTestPulseType: "qtest-pulse"
  # Optional Value to specify a seperate Pulse executor URL.
  qtestPulseExecutorUrl: ""
  qTestPulseLogLevel: "info"
  qTestPulseFlagEnableExecutorPolling: "0"
  qTestPulseWebsocketServerPort: 6001
  qTestPulseWebsocketUrl: "ws://qtest-pulse-service:6001/ws"
  swaggerUrl: https://qtest.dev.tricentis.com
  qTestPulseDeploymentEnv: "op"
  qTestPulseNodeOptions: ""
#### Ingress/IngressClass (> K8s 1.24-1.30+) #####
ingressClass:
  enabled: false
  labels: {}
  controller: ingress.k8s.aws/alb
  isDefaultClass: true
  # Use to force a networking.k8s.io API Version for certain CI/CD applications. Ex. "v1"
  fallbackApiVersion: ""
ingress:
  enabled: true
  name: pulse-ingress
  labels: {}
  annotations: {}
  canary:
    annotationPrefix: ""
    annotations: {}
    # canary-by-header: []
    # canary-by-header-pattern: []
  hosts:
    - host: pulse.qtest.local
  paths: []
  extraPaths:
    - path: /*
      backendServiceName: qtest-pulse-service
      pathType: ImplementationSpecific
      backendPort: 4080
  tls: []
  # - secretName: pulse-qtest-local-tls
  # hosts:
  # - pulse.qtest.local
  https: false
persistence:
  enabled: false
  ## Set annotations on pvc
  annotations: {}
  storageClass:
  accessMode: ReadWriteOnce
  size: 5Gi
  ## Specify extra volumes. Refer to ".spec.volumes" specification : https://kubernetes.io/fr/docs/concepts/storage/volumes/
  volumes: []
  ## Specify extra mounts. Refer to ".spec.containers.volumeMounts" specification : https://kubernetes.io/fr/docs/concepts/storage/volumes/
  mounts: []
# VPA values
vpaAutoscaling:
  enabled: false
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        controlledValues: RequestsAndLimits
# HPA values
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  healthApiPath: /
  periodSeconds: 30
  failureThreshold: 4
  targetCPUUtilizationPercentage: 85
  targetMemoryUtilizationPercentage: 85
podDisruptionBudget:
  enabled: true
resources:
  requests:
    cpu: 1
    memory: 1Gi
  limits:
    cpu: 1
    memory: 1Gi
limitRange:
  enabled: false
resourceQuota:
  enabled: false
livenessProbe:
  httpGet:
    path: /
    port: 4080
  periodSeconds: 30
livenessSslProbe:
  httpGet:
    path: /
    scheme: HTTPS
    port: 4443
  periodSeconds: 30
readinessProbe:
  httpGet:
    path: /
    port: 4080
  periodSeconds: 30
readinessSslProbe:
  httpGet:
    path: /
    scheme: HTTPS
    port: 4443
  periodSeconds: 30
startupProbe:
  httpGet:
    path: /
    port: 4080
  failureThreshold: 4
  periodSeconds: 30
startupSslProbe:
  httpGet:
    path: /
    scheme: HTTPS
    port: 4443
  failureThreshold: 4
  periodSeconds: 30
nodeSelector: {}
tolerations: []
affinity: {}
topologySpreadConstraints: {}
