apiVersion: v2
name: qtest-mgr
description: A Helm chart for qTest Manager
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application
keywords:
  - qtest-launch
  - qtest-insights
  - qtest-insights-etl
  - qtest-parameters
  - qtest-pulse
  - qtest-scenario
  - qtest-session
dependencies:
  - name: qtest-launch
    repository: "https://tricentis.github.io/qTest.Charts"
    version: "*"
    condition: qtest-launch.enabled
  - name: qtest-insights
    repository: "https://tricentis.github.io/qTest.Charts"
    version: "*"
    condition: qtest-insights.enabled
  - name: qtest-insights-etl
    repository: "https://tricentis.github.io/qTest.Charts"
    version: "*"
    condition: qtest-insights-etl.enabled
  - name: qtest-parameters
    repository: "https://tricentis.github.io/qTest.Charts"
    version: "*"
    condition: qtest-parameters.enabled
  - name: qtest-pulse
    repository: "https://tricentis.github.io/qTest.Charts"
    version: "*"
    condition: qtest-pulse.enabled
  - name: qtest-scenario
    repository: "https://tricentis.github.io/qTest.Charts"
    version: "*"
    condition: qtest-scenario.enabled
  - name: qtest-session
    repository: "https://tricentis.github.io/qTest.Charts"
    version: "*"
    condition: qtest-session.enabled
  - name: reloader
    version: "*"
    repository: "https://stakater.github.io/stakater-charts"
    condition: reloader.enabled
maintainers:
  - name: Tricentis support
    url: https://support-hub.tricentis.com/open
home: https://github.com/Tricentis-qTest/qtest-chart.git
kubeVersion: ">=1.24.0-0"
icon: https://images.g2crowd.com/uploads/product/image/social_landscape/social_landscape_c2d6524c36c94138504f7a18bf179d76/tricentis-qtest.png
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)

version: 1.12.0
# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "2025.2.4"
