apiVersion: v2
name: qtest-mgr
description: A Helm chart for qTest Manager
type: application
maintainers:
  - name: Tricentis support
    url: https://support-hub.tricentis.com/open
kubeVersion: ">=1.24.0-0"
icon: https://images.g2crowd.com/uploads/product/image/social_landscape/social_landscape_c2d6524c36c94138504f7a18bf179d76/tricentis-qtest.png
version: 1.12.7
appVersion: "2025.2.9"
