apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.serviceName }}
  namespace: {{ .Values.namespace.name }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: qtest-launch
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
    {{- if .Values.qTestLaunch.qTestLaunchSSLRequired }}
    - name: https
      protocol: TCP
      port: {{ .Values.service.targetHttpsPort }}
      targetPort: {{ .Values.service.targetHttpsPort }}
    {{- else }}
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
    {{- end }}
  selector:
    app: qtest-launch
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
---
{{- if .Values.rollouts.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.serviceName }}-canary
  namespace: {{ .Values.namespace.name }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: qtest-launch
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
    {{- if .Values.qTestLaunch.qTestLaunchSSLRequired }}
    - name: https
      protocol: TCP
      port: {{ .Values.service.targetHttpsPort }}
      targetPort: {{ .Values.service.targetHttpsPort }}
    {{- else }}
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
    {{- end }}
  selector:
    app: qtest-launch
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
{{- end }}