name: Lint and Test Charts

on:
  pull_request:
    paths:
      - 'Charts/**'

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Install Helm
        uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4.3.0
        with:
          version: 3.4.0 #renovate: datasource=github-releases depName=helm/helm
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: 3.13
      - name: Install chart-testing
        uses: helm/chart-testing-action@cf48dbf901ed202ae2c5aee26422dd6dfdf41e47 # v2.7.0
        with:
          version: v3.4.0 #renovate: datasource=github-releases depName=helm/chart-testing
      - name: Run lint
        run: ct lint --config .github/ct.yaml

  lint-docs:
    runs-on: ubuntu-latest
    needs: lint-chart
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run helm-docs
        run: sudo .github/helm-docs.sh

  kubeval-chart:
    runs-on: ubuntu-latest
    needs:
      - lint-chart
      - lint-docs
    strategy:
      matrix:
        k8s:
          # from https://github.com/instrumenta/kubernetes-json-schema
          - v1.17.4
          - v1.18.1
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Update Helm dependencies for all charts
        run: |
          for dir in ./Charts/*/; do
            helm dependency update "$dir"
          done
      - name: Run kubeval
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        run: .github/kubeval.sh

  # install-chart:
  #   name: install-chart
  #   runs-on: ubuntu-latest
  #   needs:
  #     - lint-chart
  #     - lint-docs
  #     - kubeval-chart
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2.3.4
  #       with:
  #         fetch-depth: 0
  #     - name: Create kind cluster
  #       uses: helm/kind-action@v1.1.0
  #     - name: Install chart-testing
  #       uses: helm/chart-testing-action@v2.0.1
  #       with:
  #         version: v3.3.0 #renovate: datasource=github-releases depName=helm/chart-testing
  #     - name: Run chart install
  #       run: ct install --config .github/ct.yaml
