apiVersion: v1
kind: ConfigMap
metadata:
  name: qtest-insights-i-etl-configmap
  namespace: {{ .Values.namespace.name }}
  labels:
    app: qTestInsightsIEtl
data:
  QTEST_DB_NAME: "{{ .Values.qTestInsightsIEtl.qTestInsightsIEtlDBName }}"
  QTEST_DB_HOST: "{{ .Values.qTestInsightsIEtl.qTestInsightsIEtlDBHost }}"
  QTEST_DB_USER: "{{ .Values.qTestInsightsIEtl.qTestInsightsIEtlDBUser }}"
  QTEST_DB_PORT: "{{ .Values.qTestInsightsIEtl.qTestInsightsIEtlDBPort }}"
  QTEST_DB_SCHEMA_NAME: "{{ .Values.qTestInsightsIEtl.qTestInsightsIEtlDBSchemaName }}"
  WRITE_QTEST_DB_NAME: "{{ .Values.qTestInsightsIEtl.qTestInsightsIEtlWriteQTestDBName }}"
  WRITE_QTEST_DB_HOST: "{{ .Values.qTestInsightsIEtl.qTestInsightsIEtlWriteQTestDBHost }}"
  WRITE_QTEST_DB_PORT: "{{ .Values.qTestInsightsIEtl.qTestInsightsIEtlWriteQTestDBPort }}"
  INSIGHTS_DB_SCHEMA: "{{ .Values.qTestInsightsIEtl.qTestInsightsIEtlInsightDBSchemaName }}"
  INSIGHTS_DB_USER: "{{ .Values.qTestInsightsIEtl.qTestInsightsDBUser }}"
