{{- $existingImageCredentials := .Values.imageCredentials.existingImageCredentials -}}
{{- $imageCredentials := .Values.imageCredentials.name -}}
{{- $affinity := deepCopy (default (dict) .Values.affinity) | merge (.Values.deployment.singlePodPerNode | ternary (include "qtest-insights-i-etl.podAntiAffinity" . | fromYaml) (dict)) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qtest-insights-i-etl
  namespace: {{ .Values.namespace.name }}
  {{- with .Values.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.rollouts.enabled }}
  replicas: 0
  {{- else }}
  replicas: {{ .Values.autoscaling.minReplicas }}
  {{- end }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: qtest-insights-i-etl
  strategy:
    type: {{ .Values.deployment.strategy.type }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: qtest-insights-i-etl
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
    {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
{{ toYaml . | indent 8 }}
    {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- if .Values.securityContext }}
      securityContext: {{- toYaml .Values.securityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.extraInitContainers }}
      # Currently some extra blocks accept strings
      # to continue with backwards compatibility this is being kept
      # whilst also allowing for yaml to be specified too.
      initContainers:
      {{- if eq "string" (printf "%T" .Values.extraInitContainers) }}
{{ tpl .Values.extraInitContainers . | indent 8 }}
      {{- else }}
{{ toYaml .Values.extraInitContainers | indent 8 }}
      {{- end }}
      {{- end }}
    {{ if .Values.imageCredentials.enabled }}
      {{ if .Values.imageCredentials.existingImageCredentials }}
      imagePullSecrets:
        - name: {{ $existingImageCredentials }}
      {{ else }}
      imagePullSecrets:
        - name: {{ $imageCredentials }}
      {{- end }}
    {{- end }}
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Chart.Name }}
{{- if .Values.extraArgs }}
          args:
{{- with .Values.extraArgs }}
{{ toYaml . | indent 12 }}
{{- end }}
{{- end }}
          livenessProbe:
          {{- toYaml .Values.autoscaling.livenessProbe | nindent 12 }}
          readinessProbe:
          {{- toYaml .Values.autoscaling.readinessProbe | nindent 12 }}
          startupProbe:
          {{- toYaml .Values.autoscaling.startupProbe | nindent 12 }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          ports:
          - containerPort: {{ .Values.service.targetPort }}
            name: http
            protocol: TCP
          envFrom:
            - configMapRef:
                name: qtest-insights-i-etl-configmap
          env:
            - name: QTEST_DB_PW
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: client.jdbc.postgres.password
            - name: WRITE_QTEST_DB_PW
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: client.jdbc.postgres.password
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: qtest-manager-secret
                  key: mail.password
{{- with .Values.extraEnv }}
{{ toYaml . | indent 12 }}
{{- end }}
{{- with .Values.extraVolumeMounts }}
          volumeMounts:
{{ toYaml . | indent 12 }}
{{- end }}
{{/*      {{- if .Values.extraContainers }}*/}}
{{/*      # Currently some extra blocks accept strings*/}}
{{/*      # to continue with backwards compatibility this is being kept*/}}
{{/*      # whilst also allowing for yaml to be specified too.*/}}
{{/*      {{- if eq "string" (printf "%T" .Values.extraContainers) }}*/}}
{{/*{{ tpl .Values.extraContainers . | indent 8 }}*/}}
{{/*      {{- else }}*/}}
{{/*{{ toYaml .Values.extraContainers | indent 8 }}*/}}
{{/*      {{- end }}*/}}
{{/*      {{- end }}*/}}
{{/*        - name: qtest-insights-i-etl-ephemeral*/}}
{{/*          emptyDir: {}*/}}
{{- with .Values.extraVolumes }}
      volumes:
{{ toYaml . | indent 8 }}
{{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
