{{- if and .Values.secrets.enabled (not .Values.secrets.existingConfigs) }}
apiVersion: v1
data:
  qtestDbPassword: "{{ .Values.qTestInsightsIEtl.qTestDBPassword| b64enc}}"
  insightsDbPassword: "{{ .Values.qTestInsightsIEtl.insightsDBPassword| b64enc}}"
  sessionsReadDbPassword: "{{ .Values.qTestInsightsIEtl.sessionsReadDBPassword| b64enc}}"
  sessionsWriteDbPassword: "{{ .Values.qTestInsightsIEtl.sessionsWriteDBPassword| b64enc}}"
kind: Secret
metadata:
  name: qtest-i-etl-secret
  namespace: {{ .Values.namespace.name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
type: Opaque
{{- end }}
{{- if and .Values.imageCredentials.enabled (not .Values.imageCredentials.existingImageCredentials) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imageCredentials.name }}
  namespace: {{ .Values.namespace.name }}
  {{- with .Values.liquibase.dependencyAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}