apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.serviceName }}
  namespace: {{ .Values.namespace.name }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: qtest-insights-i-etl
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    chart: {{ template "qtest-insights-i-etl.chart" . }}
spec:
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: qtest-insights-i-etl
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
---
{{- if .Values.rollouts.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.serviceName }}-canary
  namespace: {{ .Values.namespace.name }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: qtest-insights-i-etl
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    chart: {{ template "qtest-insights-i-etl.chart" . }}
spec:
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: qtest-insights-i-etl
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
{{- end }}
