{{- if .Values.vpaAutoscaling.enabled }}
{{- if not .Values.rollouts.enabled -}}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "qtest-insights-i-etl.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "qtest-insights-i-etl.labels" . | nindent 4 }}
spec:
  targetRef: 
    apiVersion: "apps/v1"
    kind: Deployment
    name: qtest-insights-i-etl
  updatePolicy:
    updateMode: {{ .Values.vpaAutoscaling.updatePolicy.updateMode | squote }}
  resourcePolicy:
    {{- with .Values.vpaAutoscaling.resourcePolicy -}}
        {{- toYaml . | nindent 4 }}
    {{- end }}
      controlledResources: ["cpu", "memory"]
{{- else }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "qtest-insights-i-etl.fullname" . }}-rollout
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "qtest-insights-i-etl.labels" . | nindent 4 }}
spec:
  targetRef: 
    apiVersion: "argoproj.io/v1alpha1"
    kind: Rollout
    name: qtest-insights-i-etl-rollout
  updatePolicy:
    updateMode: {{ .Values.vpaAutoscaling.updatePolicy.updateMode | squote }}
  resourcePolicy:
    {{- with .Values.vpaAutoscaling.resourcePolicy -}}
        {{- toYaml . | nindent 4 }}
    {{- end }}
      controlledResources: ["cpu", "memory"]
{{- end }}
{{- end }}
